language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - pip install python-coveralls

# command to run tests
script:  py.test --cov pyexchange --cov-report term-missing tests

after_success:
  - coveralls
